### ISSUE TITLE
Pull requests page is broken 

### ISSUE THREAD

**Issue by datpham23** [dragouf/Stash-Reviewers-Chrome-Extension#60] opened 2018-10-25 18:54 UTC
With Bitbucket v5.13.0 the pull requests page quickly flash w/ the original content without the extension and then it become empty.

Currently using version 2.2.15

**Comment by ra100** [comment] 2018-10-25 19:11
@datpham23 does it throw some error to console?

**Comment by datpham23** [comment] 2018-10-25 23:37
This is the error i'm seeing. 
```
stash_page.js:1549 Uncaught TypeError: self.getPullRequestsUrlBuilder is not a function
    at c.PullRequestsTable.buildUrl (stash_page.js:1549)
    at c.b.performAjax (paged-table.js?_statichash=653bd3aed116d3ce0269f2c2fae963ef-T%2F-1507964765%2F1e8d58f%2F241%2Fc572786d71039e772ed59d3b3eef4c70&locale=en-US:5)
    at c.b.requestData (paged-table.js?_statichash=653bd3aed116d3ce0269f2c2fae963ef-T%2F-1507964765%2F1e8d58f%2F241%2Fc572786d71039e772ed59d3b3eef4c70&locale=en-US:5)
    at h (paged-scrollable.js?_statichash=653bd3aed116d3ce0269f2c2fae963ef-T%2F-1507964765%2F1e8d58f%2F241%2Fc572786d71039e772ed59d3b3eef4c70&locale=en-US:2)
    at c.b.init (paged-scrollable.js?_statichash=653bd3aed116d3ce0269f2c2fae963ef-T%2F-1507964765%2F1e8d58f%2F241%2Fc572786d71039e772ed59d3b3eef4c70&locale=en-US:4)
    at c.b.init (paged-table.js?_statichash=653bd3aed116d3ce0269f2c2fae963ef-T%2F-1507964765%2F1e8d58f%2F241%2Fc572786d71039e772ed59d3b3eef4c70&locale=en-US:4)
    at Object.addPrFilters (stash_page.js:1824)
    at stash_page.js:2122
    at w (almond.js?_statichash=94f6effecdc5e19fb0d9d01f618a0651-CDN%2F-1507964765%2F1e8d58f%2F241%2F154057b82430b23e11bfb75940567a2c&locale=en-US:11)
    at almond.js?_statichash=94f6effecdc5e19fb0d9d01f618a0651-CDN%2F-1507964765%2F1e8d58f%2F241%2F154057b82430b23e11bfb75940567a2c&locale=en-US:12

```

**Comment by mrvincenzo** [comment] 2018-10-26 04:37
It is a duplicate of #57, #53

**Comment by hagnat** [comment] 2019-02-05 08:57
error reproduced and found on
Bitbucket v5.16.0
Bitbucket Server Extension 2.2.15

**Closed** 2019-05-29 12:32 UTC
